/*
 * -----------------------------------------------------------------
 * Copyright (C) 2018-2028, by Victor, All rights reserved.
 * -----------------------------------------------------------------
 * File: RouterPath
 * Author: Victor
 * Date: 2023/3/3 11:55
 * Description: 
 * -----------------------------------------------------------------
 */
export default class RouterPath {
  static readonly INDEX_PAGE = 'pages/Index';
  static readonly MAIN_PAGE = 'pages/Main';
  static readonly ALBUM_RESULT_PAGE = 'pages/AlbumResultPage';
  static readonly CONTACT_RESULT_PAGE = 'pages/ContactResultPage';
  static readonly DEVICE_RESULT_PAGE = 'pages/DeviceResultPage';
  static readonly FILE_RESULT_PAGE = 'pages/FileResultPage';
  static readonly CAPTURE_PAGE = 'pages/CapturePage';
  static readonly CAPTURE_RESULT_PAGE = 'pages/CaptureResultPage';
}